name: 发布内容到服务器 # 自动部署的名称
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤
      - name: 下载源码
        uses: actions/checkout@master

      - name: 打包构建
        uses: actions/setup-node@master
      - run: npm install # 安装第三方包
      - run: npm run docs:build # 打包

      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./docs-dist/
          scp_target: /www/wwwroot/demo/
