name: 发布内容到服务器 # 自动部署的名称
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    steps: # 步骤
      - name: 下载源码
        uses: actions/checkout@master

      - name: 打包构建
        uses: actions/setup-node@master
      - run: npm install # 安装第三方包
      - run: npm run docs:build # 打包
      - run: tar -zcvf release.tgz docs-dist

      - name: set ssh key # 临时设置 ssh key
        run: |
          mkdir -p ~/.ssh/
          echo "${{secrets.ID_RSA}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{secrets.HOST}} >> ~/.ssh/known_hosts

      - name: scp test files # 拷贝测试页面，到远程服务器
        run: |
          currentBranchName=`git branch | awk '$1 == "*"{print $2}'`

          ## 将 dist examples 移到刚创建的文件夹之内
          mv docs-dist/ $currentBranchName/dist/
          ## 将该文件夹，及其所有文件，上传到服务器
          echo current branch name is: $currentBranchName
          ssh root@${{secrets.HOST}} "rm -rf /www/wwwroot/demo"
          scp -r docs-dist/ root@${{secrets.HOST}}:www/wwwroot/demo

      - name: delete ssh key # 删除 ssh key
        run: rm -rf ~/.ssh/id_rsa
